---
title: "Lab Assignment 1 Write-Up"
output:
  html_document:
    df_print: paged
---
```{r echo=FALSE}
knitr::opts_chunk$set(comment=NA)
```

```{r loadpackages, echo=FALSE, message=FALSE}
# The following packages may be helpful for this assignment
library(dplyr)
library(ggplot2)
library(lubridate)
library(htmlTable)
library(tidyr)
```

```{r loaddata, echo=FALSE}
# Load data here
# Change directory if file is not in your working directory
load("candydata.rdata")
```

---

## Question 1

**Code**
```{r question01}
# Put your code for Q1 in this chunk
```
**Answer**

---

## Question 2

**Code**
```{r question02}
# Put your code for Q2 in this chunk
```
**Answer**

---

## Question 3

**Code**
``` {r question03}
# Put your code for Q3 in this chunk
```
**Answer**

---

## Question 4

**Code**
```{r question04}
# Put your code for Q4 in this chunk
```
**Answer**

---

## Question 5

**Code**
```{r question05}
# Put your code for Q5 in this chunk
```
**Answer**

---

## Question 6

**Code**
```{r question06}
# Put your code for Q6 in this chunk
```
**Answer**

---

## Question 7

**Code**
```{r question07}
# No code required for this question
```
**Answer**

---

## Question 8

**Code**
```{r question08}
# Put your code for Q8 in this chunk
```
**Answer**

---

## Question 9

**Code**
```{r question09}
# Put your code for Q9 in this chunk
```
**Answer**

---

## Question 10

**Answer**

