---
title: "Lab Assignment 1"
output:
  html_document:
    df_print: paged
---
```{r echo=FALSE}
knitr::opts_chunk$set(comment=NA)
```

# Overview

This lab assignment is designed to give you practice using:

* Vectors, Data Frames, Indexing, Sequencing, etc.
* Package `dplyr`
* Package `ggplot2`

The assignment uses a variety of data that comes standard with R or with packages you will load.

Use this [LA01WriteUp.Rmd](./LA01WriteUp.Rmd) file to answer the questions below.  If a question requires code, put the code in the code chunk (under **Code**). When complete, Knit the file to PDF, save that file and submit the PDF file to Canvas.  

**NOTE**: If using BGSU's Virtual Computing Lab, you cannot Knit to PDF.  In that situation, download the ".Rmd" file and submit that to Canvas.

---

## Question 1

**Question** *(8 points)*  
`rivers` is a vector of river lengths that comes with R. Load the data using `data(rivers)`.  Answer the following questions using R code.

a. What is the class of the vector `rivers`? How many items does it contain?
b. Create a new vector named `myrivers` that contains the original `rivers` vector along with the lengths of five additional rivers: 125, 193, 475, 235, and 301. Verify that the number of items in the new `myrivers` vector is the number in the original `rivers` vector plus 5. 
c. Using indexing, what is the length of the river in position 100 in the vector?  Create a new vector, `mylongrivers`, that only contains rivers that are longer than the length of the 100th river.
d. Use the `mean()` function to calculate and report the mean length of rivers in your `mylongrivers` vector.

[R Tutorial](https://jdmeyer73.github.io/MKT4320RTut/r-basics.html#basic-object-types-and-other-important-stuff){target="_blank" rel="noopener"}

---

## Question 2

**Question** *(8 points)*  
`InsectSprays` is a data frame with the count of insects (variable `count`) in an agricultural experiment treated with different insecticides (variable `spray`). Load the data using `data(InsectSprays)`. Answer the following questions using R code.

a. How many levels are in factor variable `spray`?
b. Using indexing, what is the `count` and `spray` used for row 31?
c.	Using indexing and sequencing, what is the mean `count` for row 45 through row 50?
d.	Create a new variable named `countsq` that contains the square of the count variable. What is the mean of this new variable?

[R Tutorial](https://jdmeyer73.github.io/MKT4320RTut/r-basics.html#data-frames){target="_blank" rel="noopener"}

---

## Question 3

**Question** *(7 points)*  
This question covers working directories and user-defined functions.

a. Save your name in an object called `who.am.i`
b. Find your working directory using the `getwd()` function.
c. Download the [mynameis.R](./mynameis.R) user defined function.  Save the function in your working directory that you found in part (a), and then source the function (i.e., `source("mynameis.R")`. This simple user defined function takes an object of character class with your name in it, such as your `who.am.i` object, and outputs the results in a sentence.
d. Use the user function to tell me what your name is.

[R Tutorial on Working Directory](https://jdmeyer73.github.io/MKT4320RTut/r-basics.html#setting-working-directory){target="_blank" rel="noopener"}

[R Tutorial on User Defined Functions](https://jdmeyer73.github.io/MKT4320RTut/r-basics.html#user-defined-functions){target="_blank" rel="noopener"}

---

## Question 4

**Question** *(8 points)*  
Arrests is a data frame consisting of data on Toronto arrests of people for simple possession of small quantities of marijuana.  It is part of the `car` package.

a. Load the `car` package and use `data(Arrests)` to access the data.  How many observations are in the dataset?
b. The rest of the questions will use the `dplyr` package.  Load it now.  Filter the data so that only arrests from the `year` 2000 are used and provide a count of the number of observations.  Hint: `n()` provides the number of observations.
c. Create a new variable called `log.age`, which is the natural log of the arrestee’s age. In R, `log()` provides the natural log.
d. Group the data by gender (`sex`) and by if the arrestee was released or not (`released`). Then, summarize the data to get the number of observations in each category and the mean `age` of each category. How many males were released? What is the mean `age` of females that were not released.

[R Tutorial for Loading Packages](https://jdmeyer73.github.io/MKT4320RTut/r-basics.html#packages){target="_blank" rel="noopener"}

[R Tutorial for `dplyr`](https://jdmeyer73.github.io/MKT4320RTut/r-basics.html#package-dplyr){target="_blank" rel="noopener"}

---

## Question 5

**Question** *(12 points)*  
Still using the Arrests data frame, use the `ggplot2` package to produce the following charts and answer the questions.

a. Bar chart with `year` (as a factor variable) on the x-axis and different fill colors for whether the arrestee was a citizen or not (`citizen`). Use the option `position="dodge"` in the bar chart to get side-by-side bars.  Which year did arrests peak for each category of `citizen`.
b. Column chart with each column representing the mean `age` for a `year`. Add a label to the plot using `geom_text(aes(label=round(VAR,2)), vjust=.95, color="white")` where `VAR` is the variable you created for the mean age. Which `year` had the lowest mean `age`. NOTE: This chart will require `dplyr` before sending to `ggplot`.
c.	Box plots with whiskers for each employment category (`employed`) with `age` as the continuous variable.  Which employment category appears to have more potential outliers?
d. Create a histogram for `age` with 20 bins, and assign it to an object called `p1`.  Do the same for `log.age` (created above), and assign it to an object called `p2`.  Load the package `cowplot`, and the run the following command: `plot_grid(p1,p2)`.  Which variable, `age` or `log.age`, appears to be more normally distributed?

[R Tutorial for `ggplot2`](https://jdmeyer73.github.io/MKT4320RTut/examining-and-summarizing-data.html#package-ggplot2){target="_blank" rel="noopener"}

---

## Other

**Following Instructions** *(17 points)* 
Correctly using LAB01WriteUp file with R Code in the chunks and the answers below the chunks.